name: Otomatik Finans Botu

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  haberleri-cek:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Al
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Paketleri Yukle
        run: pip install requests

      - name: Botu Calistir
        env:
          FIREBASE_API_KEY:  ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_EMAIL:    ${{ secrets.FIREBASE_EMAIL }}
          FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}
          GROQ_API_KEY:      ${{ secrets.GROQ_API_KEY }}
        run: python bot.py
