name: Otomatik Finans Botu

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir otomatik çalışır
  workflow_dispatch:       # GitHub'dan manuel butona basarak da çalıştırabilirsin

jobs:
  haberleri-cek:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Al
        uses: actions/checkout@v3
        
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Gerekli Paketleri Yükle
        run: pip install requests
        
      - name: Botu Çalıştır!
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_EMAIL: ${{ secrets.FIREBASE_EMAIL }}
          FIREBASE_PASSWORD: ${{ secrets.FIREBASE_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python bot.py